### ISSUE TITLE
Some error when running  run.sh

### ISSUE THREAD

**Issue by yangke** [a0x77n/chucky-ng#3]
Hi,Dear a0x77n
When I copied and run the run.sh in chucky_old,I got the following error.
Any suggestion to fix it?
Is there something wrong with my configuration?

```
Target source/sink is           memcpy
Target function is              35922
Maximum number of neighbors is  30
Identification of sinkes and sources ...
Warning: input line does not contain key
Warning: input line does not contain key
Warning: input line does not contain key
Warning: No config file given. Using defaults (see -D) (sally_parse_options)
Neighborhood discovery ...
Traceback (most recent call last):
  File "/usr/local/bin/knn.py", line 5, in <module>
    pkg_resources.run_script('joerntools==0.1', 'knn.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/knn.py", line 85, in <module>
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 37, in run
    self._processStream()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 52, in _processStream
    self.processLine(line.rstrip())
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/knn.py", line 51, in processLine
    self.calculateDistances()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/knn.py", line 65, in calculateDistances
    self.emb.D = self._calculateDistanceMatrix()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/knn.py", line 80, in _calculateDistanceMatrix
    return pairwise_distances(self.emb.x, metric='cosine')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/pairwise.py", line 680, in pairwise_distances
    raise TypeError("scipy distance metrics do not"
TypeError: scipy distance metrics do not support sparse matrices.
Lightweight tainting ...
Embedding of functions ...
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
sed: can't read functions/data/*: No such file or directory
chucky/function-embedding.sh: line 58: ((: *: syntax error: operand expected (error token is "*")
sed: -e expression #1, char 1: unknown command: `*'
Traceback (most recent call last):
  File "/usr/local/bin/lookup.py", line 5, in <module>
    pkg_resources.run_script('joerntools==0.1', 'lookup.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/EGG-INFO/scripts/lookup.py", line 12, in <module>
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 37, in run
    self._processStream()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 52, in _processStream
    self.processLine(line.rstrip())
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/TraversalTool.py", line 19, in processLine
    y = self.j.runGremlinQuery(query)
  File "/usr/local/lib/python2.7/dist-packages/joern-0.1-py2.7.egg/joern/all.py", line 42, in runGremlinQuery
    return self.gremlin.execute_script(finalQuery)
  File "/usr/local/lib/python2.7/dist-packages/py2neo_gremlin-0.1-py2.7.egg/py2neo_gremlin/gremlin.py", line 22, in execute_script
    rs = self._resources["execute_script"]._post({"script": script})
  File "/usr/local/lib/python2.7/dist-packages/py2neo-1.6.3-py2.7-linux-i686.egg/py2neo/neo4j.py", line 370, in _post
    raise ClientError(e)
py2neo.exceptions.ClientError: javax.script.ScriptException: java.lang.RuntimeException: org.apache.lucene.queryParser.ParseException: Cannot parse 'functionId: AND code:memcpy AND type:Symbol': Encountered " <AND> "AND "" at line 1, column 12.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...

sort: open failed: functions/data/*: No such file or directory
Warning: No config file given. Using defaults (see -D) (sally_parse_options)
Anomaly detection ...
Traceback (most recent call last):
  File "python/anomaly-score.py", line 55, in <module>
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 37, in run
    self._processStream()
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/shelltool/PipeTool.py", line 49, in _processStream
    self.streamStart()
  File "python/anomaly-score.py", line 33, in streamStart
    self.emb = self._loadEmbedding(self.args.dirname)
  File "python/anomaly-score.py", line 26, in _loadEmbedding
    return self.loader.load(dirname)
  File "/usr/local/lib/python2.7/dist-packages/joerntools-0.1-py2.7.egg/joerntools/mlutils/EmbeddingLoader.py", line 18, in load
    self.emb.x, self.emb.y = load_svmlight_file(dirname + EMBEDDING_FILENAME)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/datasets/svmlight_format.py", line 112, in load_svmlight_file
    zero_based, query_id))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/datasets/svmlight_format.py", line 210, in load_svmlight_files
    or zero_based == "auto" and all(np.min(tmp[1]) > 0 for tmp in r)):
  File "/usr/local/lib/python2.7/dist-packages/sklearn/datasets/svmlight_format.py", line 210, in <genexpr>
    or zero_based == "auto" and all(np.min(tmp[1]) > 0 for tmp in r)):
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1895, in amin
    return amin(axis, out)
ValueError: zero-size array to minimum.reduce without identity
```

My chucky.conf is:

```
SYMBOL="memcpy"
FUNCTION="35922"
K="30"
NEIGHBORS_FILE="neighbors"
BAG_OF_WORDS_DIR="bagOfWords"
FUNCTIONS_DIR="functions"
TAINT_DIR="taint"
```

The function of id:35922 is

```
/* Copy as much of MSG into BUF as possible, without corrupting errno.
   Return 0 if MSG fit in BUFLEN, otherwise return ERANGE.  */
static int
safe_copy (char *buf, size_t buflen, const char *msg)
{
  size_t len = strlen (msg);
  int ret;

  if (len < buflen)
    {
      /* Although POSIX allows memcpy() to corrupt errno, we don't
         know of any implementation where this is a real problem.  */
      memcpy (buf, msg, len + 1);
      ret = 0;
    }
  else
    {
      memcpy (buf, msg, buflen - 1);
      buf[buflen - 1] = '\0';
      ret = ERANGE;
    }
  return ret;
}
```

Chucky deems that memcpy is type: Symbol,but I find that in my neo4j database parsed by joern-master memcpy is type:Identifer
This is the AST picture
![image](https://github.com/yangke/Pet/blob/master/safe_copy.png)
Thanks very much for your attention in advance.

**Comment by fabsx00** [comment]
I think the _old-branch is discontinued. Maybe it should be removed.

**Comment by yangke** [comment]
Thank you. I tried the newer one but I don't know how to set the sink/source
Could you please tell me how to use this chucky.py argument:

```
-i {function,symbol}, --identifier-type {function,symbol}
                        The type of identifier the positional argument
                        'identifier' refers to (function, symbol).

```

I tried both

``` shell
$python chucky.py -i symbol 35922
```

and

``` shell
$python chucky.py -i function 35922
```

but they response nothing.

**Comment by a0x77n** [comment]
Hi yangke,
you have to use the name of the function/symbol not its id. If you are only interested in the pair (safe_copy, malloc) you can use the --interactive argument and skip all other pairs.
I hope this helps.

**Comment by yangke** [comment]
Thanks，but I got a new error when run the chucky.py .
When I run the command 

```
python chucky.py --interactive safe_copy
```

it throwed up 

```
Configuration: safe_copy (35923) - ret (57563)
Run configuration [(yes)/no/quit]? n
Configuration: safe_copy (35923) - buflen (57564)
Run configuration [(yes)/no/quit]? no
Configuration: safe_copy (35923) - ERANGE (57565)
Run configuration [(yes)/no/quit]? yes
Configuration skipped.
Configuration: safe_copy (35923) - memcpy (57566)
Run configuration [(yes)/no/quit]? yes
Configuration skipped.
Configuration: safe_copy (35923) - len (57567)
Run configuration [(yes)/no/quit]? yes
Configuration skipped.
Configuration: safe_copy (35923) - msg (57568)
Run configuration [(yes)/no/quit]? 
Configuration skipped.
Configuration: safe_copy (35923) - buf (57569)
Run configuration [(yes)/no/quit]? 
Configuration skipped.
```

It seems that The  Configuration will be skipped whatever I input yes or no  or use the default one by just press enter.

I create the database by this command 

```
rm -rf .joernIndex 
java -jar $JOERN/bin/joern.jar ../gzip-1.6
java -jar $JOERN/bin/udg.jar
java -jar $JOERN/bin/ddg.jar
```

Before I regenerate the database I've also got this Exception

```
Traceback (most recent call last):
  File "chucky.py", line 125, in <module>
    Chucky().execute()
  File "chucky.py", line 122, in execute
    engine.analyze(config)
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 146, in analyze
    neighborhood = self._neighborhood()
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 96, in _neighborhood
    raise subprocess.CalledProcessError(returncode, command, None)
subprocess.CalledProcessError: Command 'knn.py -k 30 --dirname .chucky/tmpuAAC6P/bag' returned non-zero exit status 1
```

**Comment by yangke** [comment]
I tried the chucky paper example of libtiff and it throws the same error as I encountered before.

```
$ python chucky.py --interactive tiffcvt
Configuration: tiffcvt (183286) - floatv (327068)
Run configuration [(yes)/no/quit]? n 
Configuration: tiffcvt (183286) - TIFFTAG_BITSPERSAMPLE (327069)
Run configuration [(yes)/no/quit]? n
Configuration: tiffcvt (183286) - TIFFTAG_ORIENTATION (327070)
Run configuration [(yes)/no/quit]? n

......
Configuration: tiffcvt (183286) - compression (327085)
Run configuration [(yes)/no/quit]? n
Configuration: tiffcvt (183286) - TIFFTAG_PLANARCONFIG (327086)
Run configuration [(yes)/no/quit]? n
Configuration: tiffcvt (183286) - width (327087)
Run configuration [(yes)/no/quit]? yes
knn.py -k 30 --dirname .chucky/tmp11Jgcd/bag
Traceback (most recent call last):
  File "chucky.py", line 125, in <module>
    Chucky().execute()
  File "chucky.py", line 122, in execute
    engine.analyze(config)
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 147, in analyze
    neighborhood = self._neighborhood()
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 97, in _neighborhood
    raise subprocess.CalledProcessError(returncode, command, None)
subprocess.CalledProcessError: Command 'knn.py -k 30 --dirname .chucky/tmp11Jgcd/bag' returned non-zero exit status 1
```

Waiting for your instruction!Thanks!

**Comment by a0x77n** [comment]
Ok, I encountered the same problem. Try to remove the chucky/cache directory (default .chucky). This should fix the python error. There are some problems with the cache if the program fails to terminate successfully.

A configuration is skipped if there are too few functions to compare. Try to use a smaller value for the number of neighbors (the -n argument)

**Comment by yangke** [comment]
I ’ve already cleaned the .chucky directory.
Moreover I removed the extracted chucky directory,and  extacted it again.
I even  tried to  decrease the knn neighbours and minimum neighbours number  to 1.
but it does not help.
The EXCEPTION return again and again.

```
......
Configuration: tiffcvt (183286) - width (327087)
Run configuration [(yes)/no/quit]? y
Traceback (most recent call last):
  File "chucky.py", line 125, in <module>
    Chucky().execute()
  File "chucky.py", line 122, in execute
    engine.analyze(config)
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 133, in analyze
    neighborhood = self._neighborhood()
  File "/home/yangke/Program/Fabian-Yamaguchi/JoernProjects/joern-projects-master/chucky/chucky_engine.py", line 89, in _neighborhood
    raise subprocess.CalledProcessError(returncode, command, None)
subprocess.CalledProcessError: Command 'knn.py -k 3 --dirname .chucky/tmpblLeMb/bag' returned non-zero exit status 1
```

the command I tried is like 

```
python chucky.py --interactive -n 3 tiffcvt
```

The current command run directory is joern-projects/chucky
and I checked that there were no .chucky directory nearby(.chucky or ../.chucky or ../../.chucky)

**Comment by a0x77n** [comment]
I commited a bug fix along with other modifications. I hope this fixes the knn issue.

**Comment by yangke** [comment]
Thanks!I tried the newer code.But it seems that the problem still exists.
In this case,  the output changes to

```
Configuration: msn_parse_oim_xml (931516) - unread (2025766)
Run configuration [(yes)/no/quit]? 
Command 'knn.py -k 3 --dirname .chucky/tmpou6R_c/bag' returned non-zero exit status 1
Do not clean up.
Configuration: msn_parse_oim_xml (931516) - iu_node (2025767)

```

I run the command ''knn.py -k 3 --dirname .chucky/tmpou6R_c/bag''
It calculate nothing and output the help info 

```
usage: knn.py [-h] [-f [FILE]] [-o [OUT]] [-e] [-k [K]] [-d [DIRNAME]] [-n]

Calculate the k nearest neighbors to a data point based on an embedding.

optional arguments:
  -h, --help            show this help message and exit
  -f [FILE], --file [FILE]
                        read input from the provided file
......
```

I tried to add -f entry and it throws the  exception:

```
.......
  File "/usr/lib/python2.7/dist-packages/sklearn/metrics/pairwise.py", line 683, in pairwise_distances
    raise TypeError("scipy distance metrics do not"
TypeError: scipy distance metrics do not support sparse matrices.

```

Maybe the cause of this problem  is the mismatch that  the embeding.libsvm is a sparce matrix
so that scipy's pairwise.py pairwise_distances function  can't calculate it's cosine distance .

**Comment by a0x77n** [comment]
I see. Sparse matrices are supported by the current master-branch of scikit-learn.

**Comment by yangke** [comment]
Nice！Thanks very much! I download the master-branch of scikit-learn and   this problem is solved but there occured another one. Please see issue #4
